const LOAD_SUCO_DE_CEVADIS_REQUEST = "suco:LOAD_SUCO_DE_CEVADIS_REQUEST";
const LOAD_SUCO_DE_CEVADIS_SUCCESS = "suco:LOAD_SUCO_DE_CEVADIS_SUCCESS";
const LOAD_SUCO_DE_CEVADIS_FAILURE = "suco:LOAD_SUCO_DE_CEVADIS_FAILURE";

export default {
  LOAD_SUCO_DE_CEVADIS_REQUEST,
  LOAD_SUCO_DE_CEVADIS_SUCCESS,
  LOAD_SUCO_DE_CEVADIS_FAILURE
};
